<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Orders</name>
   <tag></tag>
   <elementGuidId>ff3e99d0-33ae-4f2f-b1cc-bca412c96ca7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-testid=&quot;sidebar-orders&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/aside/nav/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;sidebar-orders&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c88d9856-c3a8-437a-83a0-125991cf6b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>sidebar-orders</value>
      <webElementGuid>a4e44005-29b0-45f4-95a3-46d3c12d7ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center gap-3 px-4 py-2.5 rounded-lg text-sm font-medium transition-colors
              text-gray-300 hover:bg-gray-800 hover:text-white</value>
      <webElementGuid>6fe58620-f7d5-497c-bffe-69f56e1b19fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/orders</value>
      <webElementGuid>a052392b-1fa5-4111-983e-7e51516e965f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-discover</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ef24a6cd-73d7-4286-bc4d-5966352d4a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Orders</value>
      <webElementGuid>0e7c24ed-cb2c-4b0c-981f-9df4e9ee5701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a8e27a484f14e65004ada10c8431a125</value>
      <webElementGuid>ca5e851b-3035-48be-add7-1d1acdd06c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-testid = 'sidebar-orders']</value>
      <webElementGuid>76c93eff-ca64-4583-8fe9-a1bff9de77ee</webElementGuid>
   </webElementProperties>
</WebElementEntity>
