<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_previewProduct</name>
   <tag></tag>
   <elementGuidId>f03be75c-5902-4849-af87-6718d92b8a98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[.='${userName}']/following-sibling::td//a[@id='btn-preview']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
