<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PendingProcessingCompletedCancelled</name>
   <tag></tag>
   <elementGuidId>e4d66896-8bbf-4fd3-93af-abb975f98431</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid = 'order-status-select']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-testid=&quot;order-status-select&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;order-status-select&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>30c2cc22-9105-4372-a8b5-5b66184362cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>order-status-select</value>
      <webElementGuid>ca63a386-1880-4c30-b738-fd5a0b0f3bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white</value>
      <webElementGuid>d1e0534f-10fb-42e1-920b-7130a7b2bdde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PendingProcessingCompletedCancelled</value>
      <webElementGuid>f520813b-233c-435f-9518-7c30aee04e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e0649aa021db170a2614a3201e0d8633</value>
      <webElementGuid>d0ef98ed-5b68-4c06-8f39-cecd5de68f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-testid = 'order-status-select']</value>
      <webElementGuid>2d8d6226-129a-4745-9415-abdf58dcb30b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-testid = 'order-status-select']</value>
      <webElementGuid>e13e3353-cafe-4707-96c0-28b59e96fa39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'PendingProcessingCompletedCancelled' or . = 'PendingProcessingCompletedCancelled')]</value>
      <webElementGuid>662928f4-540c-414e-8b96-1549d0adc96b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
