<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>table_Order CustomerTotalStatusActionsorder-1fe</name>
   <tag></tag>
   <elementGuidId>c50c42db-4d3b-4151-94de-16e314c063d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-testid=&quot;order-table&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/main/div/div[2]/table</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;order-table&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>table</value>
      <webElementGuid>23194034-d0e2-43d9-b31d-474dc8154b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>order-table</value>
      <webElementGuid>df266fa8-e6af-4c2f-b229-9a721502b0e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full text-sm</value>
      <webElementGuid>549479d0-f94a-4921-acc3-adca6203f3e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Order #CustomerTotalStatusActionsorder-1febrian$10.00completedORD-001Alice Johnson$239.98completedORD-002Bob Smith$89.99processing</value>
      <webElementGuid>de87768f-7795-4de8-8dc7-662ed76df263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4891e77a5c55d295430b4c54ee5e9b77</value>
      <webElementGuid>e281271d-f679-4380-bcdb-80e2b5363744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-testid = 'order-table']</value>
      <webElementGuid>163183a2-06da-4cb3-800f-257b4dc80c3e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
