<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_ORD-747</name>
   <tag></tag>
   <elementGuidId>de86f9b8-1ed9-4b4a-a089-25486aeed255</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.transition-colors:nth-child(1) td.font-medium</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' transition-colors ') and (name() = 'tr') and (position() = 1)]//td[@class and contains(concat(' ', normalize-space(@class), ' '), ' font-medium ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;ORD-747&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>df6a8c25-c4e3-44d4-8ab4-9c728a9f32d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-4 py-3 font-medium text-gray-900</value>
      <webElementGuid>9ce9224d-02f0-4d19-933c-b4419d471810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ORD-747</value>
      <webElementGuid>ceb9ac4c-a229-4a5a-82f0-11125ed26ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-26e4251158084d827987e50e0395eb3f</value>
      <webElementGuid>0082e03f-59d8-4876-8595-c7d69b5007a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' transition-colors ') and (name() = 'tr') and (position() = 1)]//td[@class and contains(concat(' ', normalize-space(@class), ' '), ' font-medium ')]</value>
      <webElementGuid>39f8bbb3-a285-49b5-b21d-33cf382d6685</webElementGuid>
   </webElementProperties>
</WebElementEntity>
