<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>table_Order CustomerTotalStatusActionsorder-1fe</name>
   <tag></tag>
   <elementGuidId>c50c42db-4d3b-4151-94de-16e314c063d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-testid=&quot;order-table&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[text()='${orderNumber}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;order-table&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>table</value>
      <webElementGuid>04148372-0eb6-4d84-8f44-fa57291d15cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>order-table</value>
      <webElementGuid>cefd857b-9390-4995-911e-45f95372979c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full text-sm</value>
      <webElementGuid>3515c586-b0b3-41c4-9c7e-0a415764b5d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Order #CustomerTotalStatusActionsorder-1febrian$10.00completedORD-001Alice Johnson$239.98completedORD-002Bob Smith$89.99processing</value>
      <webElementGuid>934fe092-6bd0-4641-bb89-f3727dd816d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4891e77a5c55d295430b4c54ee5e9b77</value>
      <webElementGuid>499dde9d-c7e3-4c03-bb08-5e0cc2af06a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-testid = 'order-table']</value>
      <webElementGuid>6dd8d3f6-ec38-4d8e-b2a3-68fef74a1363</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-testid = 'order-table']</value>
      <webElementGuid>017bbd11-c867-4068-923f-7ecfaa4068d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//table[(text() = 'Order #CustomerTotalStatusActionsorder-1febrian$10.00completedORD-001Alice Johnson$239.98completedORD-002Bob Smith$89.99processing' or . = 'Order #CustomerTotalStatusActionsorder-1febrian$10.00completedORD-001Alice Johnson$239.98completedORD-002Bob Smith$89.99processing')]</value>
      <webElementGuid>8308bf7d-e58b-49af-9510-2570fd833049</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
